version: '3.1'
services:
    db:
        container_name: db
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: start123
        volumes:
            - './docker/data/mysql:/var/lib/mysql'
    adminer:
        image: adminer
        restart: always
        depends_on:
            -   db
        links:
            -   db
        ports:
            - 8080:8080
    rabbitmq:
        image: 'docker.io/bitnami/rabbitmq:3.8-debian-10'
        environment:
            - RABBITMQ_USERNAME=admin
            - RABBITMQ_PASSWORD=start123
        ports:
            - '4369:4369'
            - '5672:5672'
            - '25672:25672'
            - '15672:15672'
        volumes:
            - './docker/data/rabbitmq:/bitnami'
