version: '3.1'
services:
    #db:
    #    container_name: db
    #    image: mysql
    #    command: --default-authentication-plugin=mysql_native_password
    #    restart: always
    #    networks:
    #        - pht-backend
    #    ports:
    #        - '3306:3306'
    #    environment:
    #        MYSQL_ROOT_PASSWORD: start123
    #    volumes:
    #        - './docker/data/mysql:/var/lib/mysql'
    #adminer:
    #    image: adminer
    #    restart: always
    #    depends_on:
    #        -   db
    #    links:
    #        -   db
    #    networks:
    #        - pht-backend
    #    ports:
    #        - 8080:8080
    rabbitmq:
        image: 'docker.io/bitnami/rabbitmq:3.8-debian-10'
        environment:
            - RABBITMQ_USERNAME=admin
            - RABBITMQ_PASSWORD=start123
        ports:
            - '4369:4369'
            - '5672:5672'
            - '25672:25672'
            - '15672:15672'
        networks:
            - pht-backend
    server:
        image: pht-server
        build: .
        networks:
            - pht-backend
        depends_on:
        #    -  db
            -  rabbitmq
        #links:
        #    -  db
        ports:
            - '3002:3000'
        restart: always
        volumes:
            - './docker/data/server:/usr/src/app/writable'
        environment:
            NODE_ENV: production
            PORT: 3000

            API_URL: http://localhost:3002/
            WEB_APP_URL: http://localhost:3000/

            VAULT_CONNECTION_STRING: s.jmMOV4W43R2zQ2WOuSQMwsV9@https://vault.pht.medic.uni-tuebingen.de/v1/
            RABBITMQ_CONNECTION_STRING: amqp://admin:start123@rabbitmq
            HARBOR_CONNECTION_STRING: pht:PangerLenis32@https://harbor.personalhealthtrain.de/api/v2.0/

            JWT_PROCEDURE: 'RSA'
            JWT_PRIVATE_KEY: writable/rsa.private
            JWT_PUBLIC_KEY: writable/rsa.public

            #TYPEORM_CONNECTION: mysql
            TYPEORM_CONNECTIO: sqlite
            TYPEORM_HOST:  db
            TYPEORM_USERNAME: root
            TYPEORM_PASSWORD: start123
            #TYPEORM_DATABASE: app
            TYPEORM_DATABASE: writable/db.sqlite
            TYPEORM_PORT: 3306
            TYPEORM_SYNCHRONIZE: 'false'
            TYPEORM_LOGGING: 'false'
            TYPEORM_ENTITIES: src/db/entities.ts
            TYPEORM_SUBSCRIBERS: src/db/subscribers.ts
            TYPEORM_SEEDING_SEEDS: src/db/seeds/**/*{.ts,.js}
networks:
    pht-backend:
        driver: bridge
