version: '3.1'
services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: start123
            MYSQL_ROOT_HOST: '%'
        ports:
            - '3306:3306'
        volumes:
            - pht_ui_db:/var/lib/mysql
    rabbitmq:
        image: 'docker.io/bitnami/rabbitmq:3.8-debian-10'
        environment:
            - RABBITMQ_USERNAME=admin
            - RABBITMQ_PASSWORD=start123
        ports:
            - '4369:4369'
            - '5672:5672'
            - '25672:25672'
            - '15672:15672'
        volumes:
            - pht_ui_rabbitmq:/bitnami
    server:
        image: pht-server
        build: .
        depends_on:
            -  db
            -  rabbitmq
        ports:
            - '3002:3000'
        restart: always
        volumes:
            - ./src:/usr/src/app/src
            - ./writable:/usr/src/app/writable
        environment:
            PORT: 3000
            TYPEORM_HOST: db
            RABBITMQ_CONNECTION_STRING: amqp://admin:start123@rabbitmq
        env_file:
            -   .env


volumes:
    pht_ui_db:
        external: true
    pht_ui_rabbitmq:
        external: true
    pht_ui_server:
        external: true
networks:
    default:
        external:
            name: pht-network
