version: '3.1'
services:
    server:
        image: pht-server
        build: .
        depends_on:
            - db
            - rabbitmq
        links:
            - db
        ports:
            - '3002:3000'
        environment:
            NODE_ENV: production
            PORT: 3004

            API_URL: http://localhost:3002/
            WEB_APP_URL: http://localhost:3000/

            VAULT_CONNECTION_STRING: s.jmMOV4W43R2zQ2WOuSQMwsV9@https://vault.pht.medic.uni-tuebingen.de/v1/
            RABBITMQ_CONNECTION_STRING: amqp://pht:start123@193.196.20.19
            HARBOR_CONNECTION_STRING: pht:PangerLenis32@https://harbor.personalhealthtrain.de/api/v2.0/

            JWT_PROCEDURE: 'RSA'
            JWT_PRIVATE_KEY: rsa.private
            JWT_PUBLIC_KEY: rsa.public

            TYPEORM_CONNECTION: mysql
            TYPEORM_HOST: db
            TYPEORM_USERNAME: root
            TYPEORM_PASSWORD: start123
            TYPEORM_DATABASE: app
            TYPEORM_PORT: 3306
            TYPEORM_SYNCHRONIZE: 'false'
            TYPEORM_LOGGING: 'true'
            TYPEORM_ENTITIES: src/db/entities.ts
            TYPEORM_SUBSCRIBERS: src/db/subscribers.ts
            TYPEORM_SEEDING_SEEDS: src/db/seeds/**/*{.ts,.js}
