name: docker

on:
    push:
        tags:
            - v*

jobs:
    push:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read

        steps:
            - uses: actions/checkout@v3

            - uses: tada5hi/action-docker-image-publish@master
              with:
                  registryPassword: ${{ secrets.GITHUB_TOKEN }}
                  registryRepository: central
                  registryTag: latest
