name: docker-nightly

on:
    schedule:
        - cron: "0 0 * * *"

jobs:
    push:
        runs-on: [ self-hosted ]
        permissions:
            packages: write
            contents: read

        steps:
            - uses: actions/checkout@v3

            - uses: tada5hi/action-docker-image-publish@master
              with:
                  registryPassword: ${{ secrets.GITHUB_TOKEN }}
                  registryRepository: central
                  registryTag: next
