# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
    push:
        branches: [ master, dev ]
    pull_request:
        branches: [ master, dev ]

env:
    PRIMARY_NODE_VERSION: 16

jobs:
    build:
        services:
            postgres:
                image: postgres:latest
                env:
                    POSTGRES_PASSWORD: start123
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

            minio:
                image: minio/minio:latest
                env:
                    MINIO_ACCESS_KEY: admin
                    MINIO_SECRET_KEY: start123
                ports:
                    - 9000:9000

            vault:
                image: vault:1.12.0
                env:
                    VAULT_DEV_ROOT_TOKEN_ID: start123
                    VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8090
                ports:
                    - 8090:8090

            redis:
                image: docker.io/bitnami/redis:latest
                env:
                    ALLOW_EMPTY_PASSWORD: yes
                ports:
                    - 6379:6379

            mq:
                image: bitnami/rabbitmq:latest
                env:
                    RABBITMQ_USERNAME: root
                    RABBITMQ_PASSWORD: start123
                ports:
                    - 5672:5672
                options: >-
                    --health-cmd "rabbitmq-diagnostics -q ping"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        runs-on: [ ubuntu-latest ]

        steps:
            - uses: actions/checkout@v3

            - name: Install
              uses: ./.github/actions/install
              with:
                 node-version: ${{ env.PRIMARY_NODE_VERSION }}

            - name: Build
              uses: ./.github/actions/build

            - name: Test
              env:
                  TYPEORM_CONNECTION: postgres
                  TYPEORM_HOST: 127.0.0.1
                  TYPEORM_USERNAME: postgres
                  TYPEORM_PASSWORD: start123
                  TYPEORM_DATABASE: test
                  SKIP_PROPOSAL_APPROVAL_OPERATION: true
                  SKIP_TRAIN_APPROVAL_OPERATION: true
              run: |
                  npm run test --workspace=packages/api
